version: '3'

services:
  2019.1-MindsY:
    image: 'mindsy'
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
     - "4000:80"

  mindsy-microservice-psychologist:
    image: 'psychologist'
    build:
      context: ../mindsy-microservice-psychologist
      dockerfile: Dockerfile
    ports: 
      - "3000:5000"
